import type { Project, APIConnector, ConnectorLog, ProjectCategory, ProjectType, SourceType } from "./types";

// ------------------------------------------------------------------
// Deterministic seed data. In production the SchedulerService writes
// these rows via connectors; here they emulate publicly-sourced feeds.
// ------------------------------------------------------------------

// Anchored to today (UTC midnight) rather than a fixed calendar date, so the
// sample dataset stays plausibly current — deadlines, "closing soon" and
// publication dates read the same way on any day the demo is opened.
const REF_DATE = (() => {
  const n = new Date();
  return Date.UTC(n.getUTCFullYear(), n.getUTCMonth(), n.getUTCDate());
})();
const DAY = 86_400_000;

function iso(offsetDays: number): string {
  return new Date(REF_DATE + offsetDays * DAY).toISOString().slice(0, 10);
}

interface Spec {
  title: string;
  organization: string;
  country: string;
  state: string;
  budget: number | null;
  currency: string;
  deadlineIn: number; // days from ref
  publishedAgo: number; // days before ref
  source: string;
  sourceType: SourceType;
  category: ProjectCategory;
  projectType: ProjectType;
  technologies: string[];
  industry: string;
  description: string;
  eligibility: string;
  contact: Project["contact"];
}

const SPECS: Spec[] = [
  {
    title: "Statewide GIS Land Records Modernization Platform",
    organization: "California Dept. of Technology",
    country: "United States",
    state: "California",
    budget: 4200000,
    currency: "USD",
    deadlineIn: 12,
    publishedAgo: 3,
    source: "SAM.gov",
    sourceType: "Government Procurement API",
    category: "GIS",
    projectType: "Government Tender",
    technologies: ["GIS", "Python", "React", "AWS", "SQL"],
    industry: "Public Sector",
    description:
      "The Department seeks a qualified vendor to design, build, and operate a statewide Geographic Information System for land and parcel records. The solution must ingest legacy CAD/GIS datasets, provide spatial search, expose an ArcGIS-compatible REST API, and support 5,000 concurrent internal users with role-based access. Deliverables include data migration, a web mapping portal built in React, automated ETL pipelines in Python, and hosting on AWS GovCloud.",
    eligibility:
      "Registered US businesses with prior state-government GIS delivery experience and SOC 2 Type II certification.",
    contact: { name: "Procurement Office", email: "rfp@cdt.ca.gov", phone: "+1-916-555-0142" },
  },
  {
    title: "AI-Powered Fraud Detection Engine for National Tax Authority",
    organization: "HM Revenue & Customs",
    country: "United Kingdom",
    state: "England",
    budget: 6800000,
    currency: "GBP",
    deadlineIn: 21,
    publishedAgo: 5,
    source: "UK Contracts Finder",
    sourceType: "Government Procurement API",
    category: "AI/ML",
    projectType: "RFP",
    technologies: ["Python", "Machine Learning", "AI", "Azure", "SQL"],
    industry: "Government",
    description:
      "HMRC requires a machine-learning platform to detect anomalous filing patterns and potential fraud across VAT and corporation-tax submissions. The system must train on historical filings, provide explainable model outputs, integrate with existing case-management tooling, and run within HMRC's Azure tenancy under strict data-residency rules.",
    eligibility: "UK-registered suppliers with G-Cloud framework listing and Cyber Essentials Plus.",
    contact: { name: "Commercial Directorate", email: "tenders@hmrc.gov.uk" },
  },
  {
    title: "Enterprise Cloud Migration — Core Banking to Azure",
    organization: "Emirates National Bank",
    country: "United Arab Emirates",
    state: "Dubai",
    budget: 9500000,
    currency: "USD",
    deadlineIn: 30,
    publishedAgo: 2,
    source: "Tender Board Portal",
    sourceType: "Public Tender API",
    category: "Cloud Migration",
    projectType: "RFP",
    technologies: ["Azure", "Java", "Spring Boot", "DevOps", "Oracle"],
    industry: "Banking & Finance",
    description:
      "Migration of the core banking application suite from on-premise Oracle Exadata to Microsoft Azure. Scope includes re-platforming Java/Spring Boot microservices, establishing CI/CD with DevOps pipelines, zero-downtime cutover strategy, and 24/7 managed operations for 18 months.",
    eligibility: "Microsoft Azure Advanced Specialization partners with regional banking references.",
    contact: { name: "Vendor Management", email: "procurement@enbd.ae", phone: "+971-4-555-0198" },
  },
  {
    title: "Digital Transformation of Municipal Citizen Services Portal",
    organization: "City of Toronto",
    country: "Canada",
    state: "Ontario",
    budget: 3100000,
    currency: "CAD",
    deadlineIn: 6,
    publishedAgo: 9,
    source: "MERX",
    sourceType: "Public Tender API",
    category: "Web Development",
    projectType: "Government Tender",
    technologies: ["React", "Node.js", "AWS", "GIS", "SQL"],
    industry: "Public Sector",
    description:
      "The City is modernizing its citizen-facing services portal to consolidate 40+ legacy web forms into a single accessible, WCAG 2.1 AA compliant platform with GIS-enabled service maps, online payments, and case tracking. Preferred stack is React with a Node.js API layer.",
    eligibility: "Vendors with public-sector accessibility experience; local presence an asset.",
    contact: { name: "Supply Chain Management", email: "bids@toronto.ca" },
  },
  {
    title: "Mobile Application for Rural Healthcare Field Workers",
    organization: "Ministry of Health & Family Welfare",
    country: "India",
    state: "Karnataka",
    budget: 1400000,
    currency: "USD",
    deadlineIn: 4,
    publishedAgo: 7,
    source: "GeM Portal",
    sourceType: "Government Procurement API",
    category: "Mobile Development",
    projectType: "Government Tender",
    technologies: ["React", "Node.js", "AWS", "AI"],
    industry: "Healthcare",
    description:
      "Development of an offline-first mobile application for community health workers to capture patient encounters, sync when connectivity is available, and surface AI-driven triage recommendations. Must support 12 regional languages and low-end Android devices.",
    eligibility: "Empanelled GeM vendors with healthcare-domain mobile delivery experience.",
    contact: { name: "e-Governance Cell", email: "tenders@mohfw.gov.in", phone: "+91-80-5550-0231" },
  },
  {
    title: "Data Engineering Platform for Smart Grid Analytics",
    organization: "Ontario Power Generation",
    country: "Canada",
    state: "Ontario",
    budget: 5200000,
    currency: "CAD",
    deadlineIn: 18,
    publishedAgo: 4,
    source: "MERX",
    sourceType: "Public Tender API",
    category: "Data Engineering",
    projectType: "RFP",
    technologies: ["Python", "AWS", "SQL", "Machine Learning", "DevOps"],
    industry: "Energy & Utilities",
    description:
      "Design of a real-time data-engineering platform ingesting smart-meter telemetry at 2M events/sec, building a lakehouse for analytics, and delivering demand-forecasting ML models. Streaming pipelines, data governance, and lineage tracking are in scope.",
    eligibility: "Firms with utility-sector data platform references and cleared personnel.",
    contact: { name: "Strategic Sourcing", email: "procurement@opg.com" },
  },
  {
    title: "Cyber Security Operations Center Build & Managed SOC",
    organization: "Federal Aviation Administration",
    country: "United States",
    state: "Virginia",
    budget: 7300000,
    currency: "USD",
    deadlineIn: 25,
    publishedAgo: 1,
    source: "SAM.gov",
    sourceType: "Government Procurement API",
    category: "Cyber Security",
    projectType: "RFP",
    technologies: ["Cyber Security", "DevOps", "Python", "AWS"],
    industry: "Aviation",
    description:
      "Establishment of a 24/7 Security Operations Center including SIEM deployment, threat-hunting playbooks, incident response, and continuous compliance monitoring against NIST 800-53. Managed operations for a base year plus four option years.",
    eligibility: "US firms with FedRAMP High experience and cleared SOC analysts.",
    contact: { name: "Contracting Officer", email: "faa-soc-rfp@faa.gov", phone: "+1-703-555-0177" },
  },
  {
    title: "Startup: Real-Time Logistics Optimization SaaS — Seed Build Partner",
    organization: "Cargofy (YC-backed)",
    country: "Germany",
    state: "Berlin",
    budget: 850000,
    currency: "EUR",
    deadlineIn: 9,
    publishedAgo: 2,
    source: "AngelList Jobs RSS",
    sourceType: "RSS Feed",
    category: "Enterprise Software",
    projectType: "Startup Announcement",
    technologies: ["Node.js", "React", "GCP", "Machine Learning", "Python"],
    industry: "Logistics",
    description:
      "Seed-stage logistics startup seeking a development partner to build the MVP of a real-time route-optimization platform. Stack is Node.js + React with ML-based ETA prediction on GCP. Equity + cash engagement considered.",
    eligibility: "Product studios comfortable with early-stage equity arrangements.",
    contact: { name: "Founder", email: "build@cargofy.io" },
  },
  {
    title: "Oracle ERP to SAP S/4HANA Migration & Rollout",
    organization: "Saudi Aramco",
    country: "Saudi Arabia",
    state: "Eastern Province",
    budget: 12500000,
    currency: "USD",
    deadlineIn: 40,
    publishedAgo: 6,
    source: "Etimad Platform",
    sourceType: "Government Procurement API",
    category: "Enterprise Software",
    projectType: "RFP",
    technologies: ["SAP", "Oracle", "Java", "Azure", "SQL"],
    industry: "Oil & Gas",
    description:
      "Full-lifecycle migration from legacy Oracle ERP to SAP S/4HANA across finance, supply chain, and HR modules for 30,000 users. Includes data migration, custom ABAP development, integration middleware, and hypercare.",
    eligibility: "SAP Gold partners with major-enterprise S/4HANA rollout track record.",
    contact: { name: "Procurement & Supply Chain", email: "sap-rfp@aramco.com" },
  },
  {
    title: "GIS-Based Flood Risk Mapping and Early Warning System",
    organization: "Environment Agency",
    country: "United Kingdom",
    state: "England",
    budget: 2900000,
    currency: "GBP",
    deadlineIn: 3,
    publishedAgo: 10,
    source: "UK Contracts Finder",
    sourceType: "Government Procurement API",
    category: "GIS",
    projectType: "Government Tender",
    technologies: ["GIS", "Python", "Machine Learning", "Azure", "React"],
    industry: "Environment",
    description:
      "Development of a national flood-risk mapping platform combining LiDAR, hydrological models, and ML nowcasting to issue early warnings. Requires GIS expertise, geospatial data engineering, and a public-facing React dashboard.",
    eligibility: "Suppliers on the Environment Agency framework with geospatial ML credentials.",
    contact: { name: "Commercial Team", email: "flood-tender@environment-agency.gov.uk" },
  },
  {
    title: "AI Chatbot & Knowledge Assistant for Citizen Support",
    organization: "Government of Singapore (GovTech)",
    country: "Singapore",
    state: "Singapore",
    budget: 2100000,
    currency: "USD",
    deadlineIn: 14,
    publishedAgo: 3,
    source: "GeBIZ",
    sourceType: "Government Procurement API",
    category: "AI/ML",
    projectType: "IT Procurement",
    technologies: ["AI", "Machine Learning", "Python", "React", "GCP"],
    industry: "Government",
    description:
      "GovTech seeks a conversational AI assistant grounded on government service knowledge bases, with retrieval-augmented generation, multilingual support, and human-handoff. Must meet government AI-governance guardrails.",
    eligibility: "Vendors registered on GeBIZ with responsible-AI delivery experience.",
    contact: { name: "GovTech Procurement", email: "ai-rfp@tech.gov.sg" },
  },
  {
    title: "DevOps Platform Engineering & Kubernetes Modernization",
    organization: "Commonwealth Bank of Australia",
    country: "Australia",
    state: "New South Wales",
    budget: 4600000,
    currency: "AUD",
    deadlineIn: 16,
    publishedAgo: 5,
    source: "TenderLink",
    sourceType: "Public Tender API",
    category: "DevOps",
    projectType: "RFQ",
    technologies: ["DevOps", "AWS", "Java", "Spring Boot", "Python"],
    industry: "Banking & Finance",
    description:
      "Build of an internal developer platform on Kubernetes with golden paths, GitOps delivery, and self-service environments for 800 engineers. Migration of Java/Spring Boot workloads to the new platform.",
    eligibility: "Certified AWS & CNCF partners with financial-services experience.",
    contact: { name: "Technology Sourcing", email: "platform-rfq@cba.com.au" },
  },
  {
    title: "Web Development — National Open Data Portal Revamp",
    organization: "Data.gov Programme Office",
    country: "United States",
    state: "District of Columbia",
    budget: 1800000,
    currency: "USD",
    deadlineIn: 8,
    publishedAgo: 4,
    source: "SAM.gov",
    sourceType: "Government Procurement API",
    category: "Web Development",
    projectType: "IT Procurement",
    technologies: ["React", "Node.js", "Python", "AWS", "SQL"],
    industry: "Public Sector",
    description:
      "Redesign and re-platform of the national open-data catalog with a modern React frontend, faceted search, dataset previews, and a developer API. Emphasis on accessibility and performance.",
    eligibility: "US 8(a) and small-business set-aside eligible vendors encouraged.",
    contact: { name: "Programme Office", email: "opendata-rfp@gsa.gov" },
  },
  {
    title: "Machine Learning Predictive Maintenance for Rail Network",
    organization: "Deutsche Bahn",
    country: "Germany",
    state: "Hesse",
    budget: 5900000,
    currency: "EUR",
    deadlineIn: 22,
    publishedAgo: 2,
    source: "TED Europa",
    sourceType: "Open Data Portal",
    category: "AI/ML",
    projectType: "RFP",
    technologies: ["Machine Learning", "Python", "Azure", "Data Engineering", "SQL"],
    industry: "Transportation",
    description:
      "Predictive-maintenance platform ingesting sensor data from rolling stock and track infrastructure to forecast failures and optimize maintenance windows. Includes data pipelines, ML models, and integration with asset-management systems.",
    eligibility: "EU suppliers with rail or heavy-industry predictive-maintenance references.",
    contact: { name: "Einkauf IT", email: "it-vergabe@deutschebahn.com" },
  },
  {
    title: "Cloud-Native E-Government Case Management System",
    organization: "Ministry of Digital Affairs",
    country: "Taiwan",
    state: "Taipei",
    budget: 3400000,
    currency: "USD",
    deadlineIn: 27,
    publishedAgo: 8,
    source: "Government e-Procurement RSS",
    sourceType: "RSS Feed",
    category: "Enterprise Software",
    projectType: "Government Tender",
    technologies: ["Java", "Spring Boot", "React", "GCP", "SQL"],
    industry: "Government",
    description:
      "Cloud-native case-management system for inter-agency workflows built on Java/Spring Boot microservices with a React frontend, deployed to GCP. Requires audit logging, RBAC, and open API documentation.",
    eligibility: "Registered IT vendors with e-government platform experience.",
    contact: { name: "Procurement Division", email: "eproc@moda.gov.tw" },
  },
  {
    title: "Angular Enterprise Portal for Insurance Claims",
    organization: "Allianz SE",
    country: "Germany",
    state: "Bavaria",
    budget: 3800000,
    currency: "EUR",
    deadlineIn: 11,
    publishedAgo: 6,
    source: "Company Procurement API",
    sourceType: "JSON Endpoint",
    category: "Enterprise Software",
    projectType: "RFQ",
    technologies: ["Angular", "Java", "Spring Boot", "Azure", "Oracle"],
    industry: "Insurance",
    description:
      "Build of an enterprise claims-processing portal using Angular on the frontend and Java/Spring Boot services, integrating with legacy Oracle systems and an Azure-hosted document store.",
    eligibility: "Preferred suppliers with insurance-domain delivery experience.",
    contact: { name: "Group Procurement", email: "it-sourcing@allianz.com" },
  },
  {
    title: "AI Document Intelligence for Legal Discovery",
    organization: "LawStack Technologies",
    country: "United States",
    state: "New York",
    budget: 1200000,
    currency: "USD",
    deadlineIn: 5,
    publishedAgo: 1,
    source: "Startup Grants RSS",
    sourceType: "RSS Feed",
    category: "AI/ML",
    projectType: "Startup Announcement",
    technologies: ["AI", "Machine Learning", "Python", "React", "AWS"],
    industry: "Legal Tech",
    description:
      "Legal-tech startup building a document-intelligence engine for e-discovery seeks an engineering partner to develop the ML pipeline (entity extraction, classification) and a React review interface.",
    eligibility: "Teams experienced with NLP and document-processing pipelines.",
    contact: { name: "CTO", email: "partners@lawstack.ai" },
  },
  {
    title: "Azure Data Lakehouse & BI Modernization",
    organization: "Woolworths Group",
    country: "Australia",
    state: "New South Wales",
    budget: 4100000,
    currency: "AUD",
    deadlineIn: 19,
    publishedAgo: 3,
    source: "TenderLink",
    sourceType: "Public Tender API",
    category: "Data Engineering",
    projectType: "RFP",
    technologies: ["Azure", "Python", "SQL", "Data Engineering", "Machine Learning"],
    industry: "Retail",
    description:
      "Modernization of the enterprise data platform to an Azure lakehouse architecture, migrating legacy warehouses, building governed data products, and enabling self-service BI for merchandising and supply-chain teams.",
    eligibility: "Microsoft data & AI specialization partners with retail references.",
    contact: { name: "Group Technology Procurement", email: "data-rfp@woolworths.com.au" },
  },
  {
    title: "Node.js API Platform for Open Banking Aggregation",
    organization: "Nordea Bank",
    country: "Sweden",
    state: "Stockholm",
    budget: 3300000,
    currency: "EUR",
    deadlineIn: 13,
    publishedAgo: 4,
    source: "Company Procurement API",
    sourceType: "JSON Endpoint",
    category: "Web Development",
    projectType: "RFQ",
    technologies: ["Node.js", "React", "AWS", "DevOps", "SQL"],
    industry: "Banking & Finance",
    description:
      "Development of a PSD2-compliant open-banking aggregation API platform in Node.js with a React developer portal, hosted on AWS with full DevOps automation and rate-limiting.",
    eligibility: "Vendors with open-banking / PSD2 delivery experience in the EU.",
    contact: { name: "Sourcing", email: "openbanking-rfq@nordea.com" },
  },
  {
    title: "GIS Utility Asset Management & Field Mobility Suite",
    organization: "Dubai Electricity & Water Authority",
    country: "United Arab Emirates",
    state: "Dubai",
    budget: 4700000,
    currency: "USD",
    deadlineIn: 2,
    publishedAgo: 12,
    source: "Tender Board Portal",
    sourceType: "Public Tender API",
    category: "GIS",
    projectType: "Government Tender",
    technologies: ["GIS", "React", "Node.js", "Azure", "SQL"],
    industry: "Energy & Utilities",
    description:
      "GIS-centric asset-management suite for water and electricity networks with field-mobility apps, network tracing, and outage management. Integration with SCADA and ERP required.",
    eligibility: "Esri partners with utility GIS implementation experience.",
    contact: { name: "Contracts Department", email: "tenders@dewa.gov.ae" },
  },
  {
    title: "Spring Boot Microservices for National Health Records",
    organization: "National Health Service (NHS Digital)",
    country: "United Kingdom",
    state: "England",
    budget: 8100000,
    currency: "GBP",
    deadlineIn: 33,
    publishedAgo: 7,
    source: "UK Contracts Finder",
    sourceType: "Government Procurement API",
    category: "Enterprise Software",
    projectType: "RFP",
    technologies: ["Java", "Spring Boot", "React", "AWS", "SQL"],
    industry: "Healthcare",
    description:
      "Re-architecture of national health-records interoperability services into Java/Spring Boot microservices with FHIR APIs, a React clinician portal, and AWS hosting under NHS security standards.",
    eligibility: "Suppliers on the NHS framework with clinical-systems experience.",
    contact: { name: "NHS Digital Commercial", email: "hr-rfp@nhs.net" },
  },
  {
    title: "Python Data Science Platform for Agricultural Yield Prediction",
    organization: "Brazilian Agricultural Research Corp (Embrapa)",
    country: "Brazil",
    state: "Distrito Federal",
    budget: 1600000,
    currency: "USD",
    deadlineIn: 15,
    publishedAgo: 5,
    source: "Open Data Portal RSS",
    sourceType: "RSS Feed",
    category: "Data Engineering",
    projectType: "IT Procurement",
    technologies: ["Python", "Machine Learning", "GIS", "GCP", "SQL"],
    industry: "Agriculture",
    description:
      "A data-science platform combining satellite imagery, weather, and soil data to predict crop yields, built in Python with GIS integration and deployed on GCP.",
    eligibility: "Research-capable vendors with geospatial data-science experience.",
    contact: { name: "Procurement", email: "licitacao@embrapa.br" },
  },
  {
    title: "Enterprise SQL Data Warehouse Consolidation",
    organization: "Telstra",
    country: "Australia",
    state: "Victoria",
    budget: 3600000,
    currency: "AUD",
    deadlineIn: 20,
    publishedAgo: 2,
    source: "TenderLink",
    sourceType: "Public Tender API",
    category: "Data Engineering",
    projectType: "RFQ",
    technologies: ["SQL", "Azure", "Python", "DevOps"],
    industry: "Telecommunications",
    description:
      "Consolidation of fragmented SQL data warehouses into a unified governed platform with automated ETL, data-quality monitoring, and Azure hosting.",
    eligibility: "Vendors with large-scale data-warehouse consolidation experience.",
    contact: { name: "Procurement Services", email: "data-rfq@telstra.com" },
  },
  {
    title: "AWS Serverless Modernization of Legacy Java Monolith",
    organization: "Banco Santander",
    country: "Spain",
    state: "Madrid",
    budget: 5400000,
    currency: "EUR",
    deadlineIn: 28,
    publishedAgo: 3,
    source: "TED Europa",
    sourceType: "Open Data Portal",
    category: "Cloud Migration",
    projectType: "RFP",
    technologies: ["AWS", "Java", "Spring Boot", "DevOps", "Node.js"],
    industry: "Banking & Finance",
    description:
      "Decomposition of a legacy Java monolith into AWS serverless and containerized services, with an event-driven architecture, CI/CD, and observability.",
    eligibility: "AWS partners with banking modernization references in the EU.",
    contact: { name: "Global Procurement", email: "cloud-rfp@santander.com" },
  },
  {
    title: "React Native Citizen Reporting App for Smart City",
    organization: "Barcelona City Council",
    country: "Spain",
    state: "Catalonia",
    budget: 1100000,
    currency: "EUR",
    deadlineIn: 7,
    publishedAgo: 6,
    source: "Government e-Procurement RSS",
    sourceType: "RSS Feed",
    category: "Mobile Development",
    projectType: "Government Tender",
    technologies: ["React", "Node.js", "GIS", "AWS"],
    industry: "Smart City",
    description:
      "A citizen-reporting mobile app enabling residents to report issues with geolocation, photos, and status tracking, integrated with the city's GIS and case-management systems.",
    eligibility: "EU vendors with smart-city or civic-tech delivery experience.",
    contact: { name: "Contractació", email: "smartcity@bcn.cat" },
  },

  // ---- JSAN-aligned opportunities: Geospatial Intelligence -----------
  {
    title: "National Geospatial Data Infrastructure & Spatial Analytics Program",
    organization: "U.S. Geological Survey",
    country: "United States",
    state: "Virginia",
    budget: 7600000,
    currency: "USD",
    deadlineIn: 24,
    publishedAgo: 2,
    source: "SAM.gov",
    sourceType: "Government Procurement API",
    category: "GIS",
    projectType: "RFP",
    technologies: ["GIS", "Python", "AWS", "Machine Learning", "Data Engineering", "SQL"],
    industry: "Government",
    description:
      "Design and operate a national geospatial data infrastructure with 3D terrain services, spatial analytics, and an open geospatial API. Scope covers geospatial data engineering, imagery pipelines, and a self-service mapping portal for federal and state agencies.",
    eligibility: "US firms with national-scale geospatial delivery and cleared personnel.",
    contact: { name: "Geospatial Program Office", email: "geo-rfp@usgs.gov", phone: "+1-703-555-0210" },
  },
  {
    title: "Geospatial Intelligence Platform for Urban Planning & Land Use",
    organization: "Abu Dhabi Urban Planning Council",
    country: "United Arab Emirates",
    state: "Abu Dhabi",
    budget: 5100000,
    currency: "USD",
    deadlineIn: 17,
    publishedAgo: 4,
    source: "Tender Board Portal",
    sourceType: "Public Tender API",
    category: "GIS",
    projectType: "Government Tender",
    technologies: ["GIS", "React", "Node.js", "Azure", "AI"],
    industry: "Urban Planning",
    description:
      "A geospatial intelligence platform combining satellite imagery, cadastral data, and AI-driven land-use classification to support master planning, zoning decisions, and infrastructure investment across the emirate.",
    eligibility: "Esri / geospatial partners with urban-planning implementation experience.",
    contact: { name: "Planning Systems", email: "gis-tender@upc.gov.ae" },
  },

  // ---- JSAN-aligned opportunities: Strategic Workforce Solutions -----
  {
    title: "Managed IT Staff Augmentation for Digital Transformation Office",
    organization: "Government of Canada — Shared Services",
    country: "Canada",
    state: "Ontario",
    budget: 8900000,
    currency: "CAD",
    deadlineIn: 15,
    publishedAgo: 3,
    source: "MERX",
    sourceType: "Public Tender API",
    category: "Workforce Solutions",
    projectType: "RFP",
    technologies: ["Java", "Python", "React", "DevOps", "AWS", "Azure"],
    industry: "Public Sector",
    description:
      "A multi-year managed staff-augmentation engagement supplying cross-functional technology teams — full-stack engineers, cloud specialists, data engineers, and scrum leads — to the federal Digital Transformation Office under an outcome-based delivery model with governance and skills-transfer obligations.",
    eligibility: "Vendors with a security-cleared bench and proven public-sector staffing frameworks.",
    contact: { name: "Talent Procurement", email: "workforce-rfp@ssc-spc.gc.ca", phone: "+1-613-555-0166" },
  },
  {
    title: "Strategic Technology Workforce & Skills Transformation Partner",
    organization: "Standard Chartered Bank",
    country: "Singapore",
    state: "Singapore",
    budget: 6200000,
    currency: "USD",
    deadlineIn: 9,
    publishedAgo: 5,
    source: "Company Procurement API",
    sourceType: "JSON Endpoint",
    category: "Workforce Solutions",
    projectType: "RFQ",
    technologies: ["Java", "Spring Boot", "AWS", "DevOps", "Machine Learning"],
    industry: "Banking & Finance",
    description:
      "Selection of a strategic workforce partner to build and manage blended onshore/offshore engineering pods, run capability academies for cloud and AI upskilling, and provide flexible scaling across the bank's technology programs.",
    eligibility: "Consultancies with managed-capacity delivery and regional talent networks.",
    contact: { name: "Global Sourcing", email: "workforce@sc.com" },
  },

  // ---- JSAN-aligned opportunities: Structured Program Management -----
  {
    title: "Enterprise PMO Setup & Program Governance for Digital Programs",
    organization: "Qatar Ministry of Transport",
    country: "Qatar",
    state: "Doha",
    budget: 4400000,
    currency: "USD",
    deadlineIn: 20,
    publishedAgo: 2,
    source: "Etimad Platform",
    sourceType: "Government Procurement API",
    category: "Program Management",
    projectType: "RFP",
    technologies: ["DevOps", "SQL", "Enterprise Software"],
    industry: "Transportation",
    description:
      "Establishment of an enterprise Program Management Office to govern a portfolio of digital and infrastructure programs — delivering governance frameworks, stage-gate controls, benefits realization tracking, risk management, and executive reporting dashboards.",
    eligibility: "Firms with PMO establishment and large-program governance credentials (PMI/MSP).",
    contact: { name: "Program Governance", email: "pmo-rfp@mot.gov.qa" },
  },
  {
    title: "Structured Program Management for Smart City Delivery",
    organization: "City of Melbourne",
    country: "Australia",
    state: "Victoria",
    budget: 3500000,
    currency: "AUD",
    deadlineIn: 6,
    publishedAgo: 7,
    source: "TenderLink",
    sourceType: "Public Tender API",
    category: "Program Management",
    projectType: "RFQ",
    technologies: ["GIS", "DevOps", "Data Engineering"],
    industry: "Smart City",
    description:
      "Structured program-management services to coordinate a multi-vendor smart-city delivery portfolio — integrating GIS, IoT, and data platforms — with schedule integration, dependency management, vendor governance, and outcome assurance across workstreams.",
    eligibility: "Program-management specialists with smart-city or multi-vendor integration experience.",
    contact: { name: "Program Delivery Office", email: "program-rfq@melbourne.vic.gov.au" },
  },

  // ==================================================================
  //  CORE BUSINESS — GIS & Telecom opportunities
  // ==================================================================
  {
    title: "GIS Fibre Network Inventory & Outside-Plant Management Platform",
    organization: "BT Openreach",
    country: "United Kingdom",
    state: "England",
    budget: 6200000,
    currency: "GBP",
    deadlineIn: 16,
    publishedAgo: 2,
    source: "UK Contracts Finder",
    sourceType: "Government Procurement API",
    category: "Telecom / Network",
    projectType: "RFP",
    technologies: ["GIS", "Fiber Optics", "OSS/BSS", "Python", "SQL"],
    industry: "Telecommunications",
    description:
      "Design and operate a GIS-based outside-plant (OSP) inventory platform covering ducts, cabinets, poles, and fibre routes across the access network. The solution must model the physical and logical network, support network tracing and capacity planning, integrate with OSS/BSS, and give field engineers a mobile mapping app.",
    eligibility: "Suppliers with telecom OSP/GIS delivery experience and cleared field personnel.",
    contact: { name: "Network Procurement", email: "osp-rfp@openreach.co.uk", phone: "+44-20-5550-0164" },
  },
  {
    title: "5G Radio Access Network Rollout Planning & Geospatial Analytics",
    organization: "Deutsche Telekom",
    country: "Germany",
    state: "North Rhine-Westphalia",
    budget: 8400000,
    currency: "EUR",
    deadlineIn: 23,
    publishedAgo: 3,
    source: "TED Europa",
    sourceType: "Open Data Portal",
    category: "Telecom / Network",
    projectType: "RFP",
    technologies: ["5G", "RF Planning", "GIS", "Python", "Machine Learning"],
    industry: "Telecommunications",
    description:
      "A geospatial planning platform for 5G RAN rollout: site selection, RF propagation and coverage prediction, capacity modelling, and permitting workflow. Combines terrain and clutter data with drive-test and OSS performance data to optimise cell placement across urban and rural areas.",
    eligibility: "EU vendors with RF planning and geospatial analytics credentials in mobile networks.",
    contact: { name: "Access Network Sourcing", email: "ran-rfp@telekom.de" },
  },
  {
    title: "Nationwide Fibre-to-the-Home GIS Design & Rollout Platform",
    organization: "National Broadband Ireland",
    country: "Ireland",
    state: "Leinster",
    budget: 7100000,
    currency: "EUR",
    deadlineIn: 11,
    publishedAgo: 4,
    source: "TED Europa",
    sourceType: "Open Data Portal",
    category: "GIS",
    projectType: "Government Tender",
    technologies: ["GIS", "Fiber Optics", "Network Planning", "React", "AWS"],
    industry: "Telecommunications",
    description:
      "GIS-driven FTTH design and rollout platform for the national broadband programme — automated network design, splice and route planning, premises-passed tracking, and a public coverage-lookup portal built in React on AWS.",
    eligibility: "Firms with national fibre design/GIS experience; local presence an asset.",
    contact: { name: "Deployment Office", email: "ftth-tender@nbi.ie" },
  },
  {
    title: "Telecom OSS/BSS Modernization & Network Assurance",
    organization: "Singtel",
    country: "Singapore",
    state: "Singapore",
    budget: 9000000,
    currency: "USD",
    deadlineIn: 27,
    publishedAgo: 5,
    source: "Company Procurement API",
    sourceType: "JSON Endpoint",
    category: "Telecom / Network",
    projectType: "RFP",
    technologies: ["OSS/BSS", "Java", "Spring Boot", "SQL", "DevOps"],
    industry: "Telecommunications",
    description:
      "Modernization of operational and business support systems (OSS/BSS) — service inventory, fault and performance management, order orchestration, and network assurance — re-platformed onto Java/Spring Boot microservices with automated CI/CD.",
    eligibility: "Systems integrators with carrier-grade OSS/BSS transformation references.",
    contact: { name: "Network IT Procurement", email: "ossbss-rfp@singtel.com" },
  },
  {
    title: "Mobile Coverage, Spectrum & Drive-Test GIS Analytics Platform",
    organization: "Federal Communications Commission",
    country: "United States",
    state: "District of Columbia",
    budget: 4600000,
    currency: "USD",
    deadlineIn: 8,
    publishedAgo: 2,
    source: "SAM.gov",
    sourceType: "Government Procurement API",
    category: "GIS",
    projectType: "RFP",
    technologies: ["GIS", "5G", "Python", "Machine Learning", "AWS"],
    industry: "Telecommunications",
    description:
      "A geospatial analytics platform ingesting carrier coverage filings, spectrum licences, and crowd-sourced drive-test data to map mobile coverage and validate broadband availability, with ML-based gap detection and a public map viewer.",
    eligibility: "US firms with geospatial data-science experience; small-business set-asides encouraged.",
    contact: { name: "Office of Economics & Analytics", email: "coverage-rfp@fcc.gov" },
  },
  {
    title: "Utility Pole & Telecom Asset Field GIS Survey and Audit",
    organization: "SaskTel",
    country: "Canada",
    state: "Saskatchewan",
    budget: 3200000,
    currency: "CAD",
    deadlineIn: 5,
    publishedAgo: 8,
    source: "MERX",
    sourceType: "Public Tender API",
    category: "GIS",
    projectType: "Government Tender",
    technologies: ["GIS", "Node.js", "React", "Azure"],
    industry: "Telecommunications",
    description:
      "Field GIS survey and audit of utility poles and attached telecom assets across the provincial network — mobile data capture, condition assessment, joint-use reconciliation, and a GIS asset register with an inspection dashboard.",
    eligibility: "Vendors with field GIS survey capability and telecom asset experience.",
    contact: { name: "Supply Management", email: "gis-survey@sasktel.com" },
  },
  {
    title: "Smart Metering & IoT Network Rollout with GIS Integration",
    organization: "Telstra IoT",
    country: "Australia",
    state: "Queensland",
    budget: 5100000,
    currency: "AUD",
    deadlineIn: 18,
    publishedAgo: 3,
    source: "TenderLink",
    sourceType: "Public Tender API",
    category: "Telecom / Network",
    projectType: "RFQ",
    technologies: ["Network Planning", "GIS", "Data Engineering", "Azure", "Python"],
    industry: "Telecommunications",
    description:
      "Rollout of a smart-metering and IoT connectivity network with GIS-based gateway placement, coverage planning, device inventory, and a telemetry data platform for meter and sensor data at scale.",
    eligibility: "Firms with IoT/LPWAN network rollout and geospatial planning experience.",
    contact: { name: "IoT Sourcing", email: "iot-rfq@telstra.com" },
  },
  {
    title: "Subsea & Backbone Cable Route GIS Planning and Permitting",
    organization: "du (Emirates Integrated Telecommunications)",
    country: "United Arab Emirates",
    state: "Dubai",
    budget: 6800000,
    currency: "USD",
    deadlineIn: 24,
    publishedAgo: 4,
    source: "Tender Board Portal",
    sourceType: "Public Tender API",
    category: "GIS",
    projectType: "Government Tender",
    technologies: ["GIS", "Fiber Optics", "Python", "AWS", "SQL"],
    industry: "Telecommunications",
    description:
      "GIS platform for planning long-haul and subsea backbone cable routes — bathymetry and terrain analysis, route optimisation, landing-station siting, permitting and stakeholder workflow, and as-built route documentation.",
    eligibility: "Suppliers with backbone/subsea route-engineering and GIS credentials.",
    contact: { name: "Network Planning", email: "backbone-tender@du.ae" },
  },

  // ==================================================================
  //  GIS & Telecom opportunities from around the world
  // ==================================================================
  {
    title: "5G & Fibre GIS Network Planning for the Klang Valley",
    organization: "Telekom Malaysia",
    country: "Malaysia",
    state: "Kuala Lumpur",
    budget: 5400000,
    currency: "USD",
    deadlineIn: 19,
    publishedAgo: 3,
    source: "ePerolehan Malaysia",
    sourceType: "Public Tender API",
    category: "Telecom / Network",
    projectType: "RFP",
    technologies: ["GIS", "5G", "Fiber Optics", "Network Planning", "Python"],
    industry: "Telecommunications",
    description:
      "GIS-based planning platform for combined 5G and fibre rollout across the Klang Valley — site and route design, coverage prediction, capacity modelling, and an OSP inventory feeding into network operations.",
    eligibility: "Registered vendors with telecom GIS/network planning experience in Malaysia.",
    contact: { name: "Network Procurement", email: "network-rfp@tm.com.my" },
  },
  {
    title: "National Digital Cadastre & Land GIS Modernization",
    organization: "Department of Survey & Mapping Malaysia (JUPEM)",
    country: "Malaysia",
    state: "Kuala Lumpur",
    budget: 3900000,
    currency: "USD",
    deadlineIn: 26,
    publishedAgo: 6,
    source: "ePerolehan Malaysia",
    sourceType: "Government Procurement API",
    category: "GIS",
    projectType: "Government Tender",
    technologies: ["GIS", "Python", "React", "AWS", "SQL"],
    industry: "Public Sector",
    description:
      "Modernization of the national digital cadastre — coordinated cadastral database, survey data migration, spatial validation, and a public land-information portal.",
    eligibility: "Licensed survey/GIS firms with national cadastre experience.",
    contact: { name: "Procurement Unit", email: "tender@jupem.gov.my" },
  },
  {
    title: "Fibre-to-the-Home GIS Rollout — Île-de-France",
    organization: "Orange",
    country: "France",
    state: "Île-de-France",
    budget: 6600000,
    currency: "EUR",
    deadlineIn: 14,
    publishedAgo: 4,
    source: "TED Europa",
    sourceType: "Open Data Portal",
    category: "GIS",
    projectType: "RFP",
    technologies: ["GIS", "Fiber Optics", "Network Planning", "Node.js", "AWS"],
    industry: "Telecommunications",
    description:
      "GIS-driven FTTH design and rollout across the Île-de-France region — automated network design, splice/route planning, premises-passed tracking, and field mobility.",
    eligibility: "EU suppliers with high-volume fibre design/GIS delivery experience.",
    contact: { name: "Achats Réseau", email: "ftth-rfp@orange.com" },
  },
  {
    title: "Rail Telecom & GSM-R Network GIS Asset Management",
    organization: "SNCF Réseau",
    country: "France",
    state: "Île-de-France",
    budget: 4800000,
    currency: "EUR",
    deadlineIn: 21,
    publishedAgo: 5,
    source: "TED Europa",
    sourceType: "Open Data Portal",
    category: "Telecom / Network",
    projectType: "RFP",
    technologies: ["GIS", "Network Planning", "Python", "Azure", "SQL"],
    industry: "Transportation",
    description:
      "GIS asset-management platform for trackside telecom and GSM-R/FRMCS networks — cable and equipment inventory, network tracing, maintenance planning, and migration support to FRMCS.",
    eligibility: "Suppliers with rail telecom and geospatial asset experience.",
    contact: { name: "Direction des Achats", email: "telecom-gis@sncf-reseau.fr" },
  },
  {
    title: "Nationwide 5G Coverage Planning & Spectrum GIS",
    organization: "Play (P4)",
    country: "Poland",
    state: "Masovia",
    budget: 5200000,
    currency: "EUR",
    deadlineIn: 17,
    publishedAgo: 3,
    source: "TED Europa",
    sourceType: "Open Data Portal",
    category: "Telecom / Network",
    projectType: "RFQ",
    technologies: ["5G", "RF Planning", "GIS", "Machine Learning", "Python"],
    industry: "Telecommunications",
    description:
      "Geospatial 5G coverage and capacity planning platform with spectrum management, RF propagation modelling, and ML-based site optimisation for a national mobile network.",
    eligibility: "Vendors with RF planning and geospatial analytics in mobile networks.",
    contact: { name: "Network Sourcing", email: "ran-rfq@play.pl" },
  },
  {
    title: "Subsea Fibre Route & Landing-Station GIS Planning",
    organization: "Telenor",
    country: "Norway",
    state: "Oslo",
    budget: 6100000,
    currency: "EUR",
    deadlineIn: 25,
    publishedAgo: 2,
    source: "TED Europa",
    sourceType: "Open Data Portal",
    category: "GIS",
    projectType: "RFP",
    technologies: ["GIS", "Fiber Optics", "Python", "AWS", "Data Engineering"],
    industry: "Telecommunications",
    description:
      "GIS platform for subsea and coastal fibre route planning — bathymetry analysis, route optimisation, landing-station siting, marine permitting, and as-built documentation.",
    eligibility: "Suppliers with subsea route-engineering and GIS credentials.",
    contact: { name: "Network Procurement", email: "subsea-rfp@telenor.no" },
  },
  {
    title: "Power-Grid & Telecom Corridor GIS Analytics",
    organization: "Statnett",
    country: "Norway",
    state: "Oslo",
    budget: 4300000,
    currency: "EUR",
    deadlineIn: 12,
    publishedAgo: 7,
    source: "TED Europa",
    sourceType: "Open Data Portal",
    category: "GIS",
    projectType: "Government Tender",
    technologies: ["GIS", "Data Engineering", "Python", "Azure", "Machine Learning"],
    industry: "Energy & Utilities",
    description:
      "Geospatial analytics for shared power and telecom corridors — right-of-way management, vegetation and encroachment analysis, and asset condition monitoring across the transmission network.",
    eligibility: "Firms with utility/telecom corridor GIS experience.",
    contact: { name: "Innkjøp", email: "gis-tender@statnett.no" },
  },
  {
    title: "e-Government Geospatial Data Platform (X-Road)",
    organization: "Estonian Land Board",
    country: "Estonia",
    state: "Harju",
    budget: 2700000,
    currency: "EUR",
    deadlineIn: 15,
    publishedAgo: 4,
    source: "TED Europa",
    sourceType: "Open Data Portal",
    category: "GIS",
    projectType: "IT Procurement",
    technologies: ["GIS", "Node.js", "React", "AWS", "SQL"],
    industry: "Government",
    description:
      "A national geospatial data platform integrated with the X-Road interoperability layer — spatial data services, an open map portal, and API access for public and private consumers.",
    eligibility: "EU vendors with e-government and geospatial platform experience.",
    contact: { name: "Procurement", email: "geoportal@maaamet.ee" },
  },
  {
    title: "Telangana Fibre Grid GIS & OSS Integration",
    organization: "Telangana Fibre Grid (T-Fiber)",
    country: "India",
    state: "Telangana",
    budget: 4400000,
    currency: "USD",
    deadlineIn: 9,
    publishedAgo: 3,
    source: "GeM Portal",
    sourceType: "Government Procurement API",
    category: "Telecom / Network",
    projectType: "Government Tender",
    technologies: ["GIS", "Fiber Optics", "OSS/BSS", "Python", "SQL"],
    industry: "Telecommunications",
    description:
      "GIS and OSS integration for the state fibre grid — network inventory, route and splice management, service provisioning workflow, and a household connectivity dashboard.",
    eligibility: "Empanelled vendors with fibre GIS/OSS delivery experience.",
    contact: { name: "T-Fiber Procurement", email: "tenders@tfiber.telangana.gov.in" },
  },
  {
    title: "Smart City GIS & Utility Network Mapping — Hyderabad",
    organization: "Greater Hyderabad Municipal Corporation",
    country: "India",
    state: "Telangana",
    budget: 3100000,
    currency: "USD",
    deadlineIn: 6,
    publishedAgo: 8,
    source: "GeM Portal",
    sourceType: "Government Procurement API",
    category: "GIS",
    projectType: "Government Tender",
    technologies: ["GIS", "React", "Node.js", "Azure", "Data Engineering"],
    industry: "Smart City",
    description:
      "City-wide GIS and utility network mapping — water, sewerage, power, and telecom assets — with a 3D base map, field survey, and an integrated works-management dashboard.",
    eligibility: "Firms with municipal GIS and utility mapping experience.",
    contact: { name: "GHMC e-Governance", email: "gis-tender@ghmc.gov.in" },
  },
  {
    title: "Statewide Broadband Fibre GIS & Availability Mapping",
    organization: "New Jersey Board of Public Utilities",
    country: "United States",
    state: "New Jersey",
    budget: 4900000,
    currency: "USD",
    deadlineIn: 20,
    publishedAgo: 2,
    source: "SAM.gov",
    sourceType: "Government Procurement API",
    category: "GIS",
    projectType: "RFP",
    technologies: ["GIS", "Fiber Optics", "Python", "AWS", "Machine Learning"],
    industry: "Telecommunications",
    description:
      "Statewide broadband GIS platform — fibre and service-availability mapping, address-level serviceability, grant-area analysis, and a public broadband map to support funding decisions.",
    eligibility: "US firms with broadband/GIS mapping experience; set-asides encouraged.",
    contact: { name: "Division of Broadband", email: "broadband-rfp@bpu.nj.gov" },
  },
  {
    title: "5G Small-Cell Site GIS Planning — Stockholm",
    organization: "Telia",
    country: "Sweden",
    state: "Stockholm",
    budget: 3600000,
    currency: "EUR",
    deadlineIn: 13,
    publishedAgo: 5,
    source: "TED Europa",
    sourceType: "Open Data Portal",
    category: "Telecom / Network",
    projectType: "RFQ",
    technologies: ["5G", "RF Planning", "GIS", "Python", "Azure"],
    industry: "Telecommunications",
    description:
      "GIS-based small-cell site planning for dense urban 5G — candidate identification on street furniture, RF coverage prediction, permitting workflow, and rollout tracking.",
    eligibility: "Vendors with small-cell/RF planning and geospatial experience.",
    contact: { name: "Network Sourcing", email: "smallcell-rfq@telia.se" },
  },
  {
    title: "Municipal Fibre & Duct GIS Inventory Platform",
    organization: "Toronto Hydro Telecom",
    country: "Canada",
    state: "Ontario",
    budget: 3800000,
    currency: "CAD",
    deadlineIn: 16,
    publishedAgo: 4,
    source: "MERX",
    sourceType: "Public Tender API",
    category: "GIS",
    projectType: "RFP",
    technologies: ["GIS", "Fiber Optics", "Node.js", "React", "Azure"],
    industry: "Telecommunications",
    description:
      "GIS inventory of municipal fibre and duct infrastructure — capacity and occupancy tracking, joint-use management, and a self-service availability lookup for enterprise customers.",
    eligibility: "Vendors with municipal fibre/GIS inventory experience.",
    contact: { name: "Supply Chain", email: "fibre-gis@torontohydro.com" },
  },
  {
    title: "Berlin Metropolitan Fibre GIS Design & Rollout",
    organization: "Vodafone Deutschland",
    country: "Germany",
    state: "Berlin",
    budget: 5700000,
    currency: "EUR",
    deadlineIn: 22,
    publishedAgo: 3,
    source: "TED Europa",
    sourceType: "Open Data Portal",
    category: "Telecom / Network",
    projectType: "RFP",
    technologies: ["GIS", "Fiber Optics", "Network Planning", "Python", "AWS"],
    industry: "Telecommunications",
    description:
      "Metropolitan fibre GIS design and rollout across Berlin — automated network design, permitting, civil-works coordination, and premises-passed tracking with an operations dashboard.",
    eligibility: "EU suppliers with metropolitan fibre design/GIS experience.",
    contact: { name: "Einkauf Netz", email: "fibre-rfp@vodafone.de" },
  },
];

const CATEGORIES: ProjectCategory[] = [
  "GIS",
  "AI/ML",
  "Cloud Migration",
  "Web Development",
  "Mobile Development",
  "Data Engineering",
  "Enterprise Software",
  "Cyber Security",
  "DevOps",
  "Telecom / Network",
  "Workforce Solutions",
  "Program Management",
];

// ---- JSAN service-line mapping + capability fit scoring ---------------
const SERVICE_LINE_BY_CATEGORY: Record<ProjectCategory, import("./types").ServiceLine> = {
  GIS: "Geospatial Intelligence",
  "Telecom / Network": "Telecom & Network Engineering",
  "Geospatial / Telecom Adjacent": "Geospatial & Telecom Adjacent",
  "Workforce Solutions": "Strategic Workforce Solutions",
  "Program Management": "Structured Program Management",
  "AI/ML": "Digital Engineering",
  "Cloud Migration": "Digital Engineering",
  "Web Development": "Digital Engineering",
  "Mobile Development": "Digital Engineering",
  "Data Engineering": "Digital Engineering",
  "Enterprise Software": "Digital Engineering",
  "Cyber Security": "Digital Engineering",
  DevOps: "Digital Engineering",
};

// Technologies at the core of JSAN's delivery capability — GIS and telecom
// network engineering lead, alongside the digital-engineering stack.
const JSAN_CORE_TECH = new Set([
  "GIS", "5G", "Fiber Optics", "OSS/BSS", "Network Planning", "RF Planning", "LTE",
  "Python", "Java", "Spring Boot", "React", "Angular", "Node.js",
  "AWS", "Azure", "GCP", "AI", "Machine Learning", "DevOps", "SQL", "Data Engineering",
]);

function serviceLineFor(category: ProjectCategory): import("./types").ServiceLine {
  return SERVICE_LINE_BY_CATEGORY[category];
}

// Deterministic 0–100 relevance score. GIS (geospatial) and telecom network
// engineering are JSAN's core business, so they carry the highest base scores;
// depth of core-tech overlap adds the rest.
function fitScoreFor(category: ProjectCategory, technologies: string[]): number {
  const base: Record<import("./types").ServiceLine, number> = {
    "Geospatial Intelligence": 92,
    "Telecom & Network Engineering": 90,
    "Geospatial & Telecom Adjacent": 84,
    "Strategic Workforce Solutions": 82,
    "Structured Program Management": 78,
    "Digital Engineering": 74,
  };
  const line = serviceLineFor(category);
  const overlap = technologies.filter((t) => JSAN_CORE_TECH.has(t)).length;
  const score = base[line] + Math.min(overlap * 2, 12);
  return Math.max(60, Math.min(99, score));
}

const rate: Record<string, number> = { USD: 1, GBP: 1.27, EUR: 1.08, CAD: 0.73, AUD: 0.66 };

function usd(amount: number | null, currency: string): number | null {
  if (amount == null) return null;
  return Math.round(amount * (rate[currency] ?? 1));
}

function statusOf(deadlineIn: number): Project["status"] {
  if (deadlineIn < 0) return "Closed";
  if (deadlineIn <= 7) return "Closing Soon";
  return "Open";
}

function summarize(desc: string): string {
  const first = desc.split(". ")[0];
  return first.length > 180 ? first.slice(0, 177) + "…" : first + ".";
}

// Maps each public source to its real, working portal. The project title is
// used as the search query so the link opens a live, relevant results page.
function officialLinkFor(source: string, title: string): string {
  const q = encodeURIComponent(title);
  const map: Record<string, string> = {
    "SAM.gov": `https://sam.gov/search/?keywords=${q}&index=opp`,
    "UK Contracts Finder": `https://www.contractsfinder.service.gov.uk/Search/Results?&searchTerm=${q}`,
    "TED Europa": `https://ted.europa.eu/en/search/result?text=${q}`,
    "MERX": `https://www.merx.com/public/solicitations/open`,
    "GeM Portal": `https://bidplus.gem.gov.in/all-bids`,
    "Tender Board Portal": `https://duckduckgo.com/?q=${q}+tender`,
    "AngelList Jobs RSS": `https://wellfound.com/`,
    "Etimad Platform": `https://tenders.etimad.sa/Tender/AllTendersForVisitor`,
    "GeBIZ": `https://www.gebiz.gov.sg/`,
    "ePerolehan Malaysia": `https://www.eperolehan.gov.my/`,
    "TenderLink": `https://www.tenderlink.com/`,
    "Government e-Procurement RSS": `https://duckduckgo.com/?q=${q}+e-procurement`,
    "Startup Grants RSS": `https://duckduckgo.com/?q=${q}`,
    "Open Data Portal RSS": `https://duckduckgo.com/?q=${q}+open+data`,
    "Company Procurement API": `https://duckduckgo.com/?q=${q}+RFP`,
  };
  return map[source] ?? `https://duckduckgo.com/?q=${q}`;
}

function tagsFor(s: Spec): string[] {
  const tags = new Set<string>();
  tags.add(serviceLineFor(s.category));
  tags.add(s.category);
  tags.add(s.industry);
  if (s.budget && usd(s.budget, s.currency)! > 5_000_000) tags.add("High Value");
  if (s.deadlineIn <= 7) tags.add("Urgent");
  s.technologies.slice(0, 2).forEach((t) => tags.add(t));
  return [...tags];
}

// A discovery feed always surfaces tenders that have since been awarded to a
// competitor — these are "occupied" and no longer pursuable. Marking a
// deterministic spread of records as Awarded keeps the sample honest and gives
// the Explorer's "Hide occupied" filter something real to act on.
const AWARDED_INDICES = new Set([3, 9, 16, 22, 29, 35, 41, 48]);

export const PROJECTS: Project[] = SPECS.map((s, i) => {
  const budgetUsd = usd(s.budget, s.currency);
  const status: Project["status"] = AWARDED_INDICES.has(i) ? "Awarded" : statusOf(s.deadlineIn);
  return {
    id: `PRJ-${String(1001 + i)}`,
    referenceNumber: `${s.source.replace(/[^A-Z]/gi, "").slice(0, 4).toUpperCase()}-2026-${String(4820 + i * 7)}`,
    title: s.title,
    originalTitle: s.title, // sample data is authored in English; nothing to translate
    description: s.description,
    summary: summarize(s.description),
    organization: s.organization,
    country: s.country,
    state: s.state,
    budget: budgetUsd,
    budgetLabel:
      budgetUsd == null
        ? "Undisclosed"
        : `${s.currency} ${(s.budget! / 1_000_000).toFixed(1)}M`,
    currency: s.currency,
    deadline: iso(s.deadlineIn),
    publicationDate: iso(-s.publishedAgo),
    source: s.source,
    sourceType: s.sourceType,
    category: s.category,
    serviceLine: serviceLineFor(s.category),
    fitScore: fitScoreFor(s.category, s.technologies),
    projectType: s.projectType,
    status,
    technologies: s.technologies,
    tags: tagsFor(s),
    eligibility: s.eligibility,
    officialLink: officialLinkFor(s.source, s.title),
    contact: s.contact,
    industry: s.industry,
  };
});

export const CONNECTORS: APIConnector[] = [
  {
    id: "CON-01",
    name: "SAM.gov Contract Opportunities",
    sourceType: "Government Procurement API",
    baseUrl: "https://api.sam.gov/opportunities/v2/search",
    authType: "API Key",
    enabled: true,
    schedule: "Hourly",
    rateLimitPerMin: 60,
    pagination: "Offset",
    retryPolicy: "Exponential backoff, 3 attempts",
    lastRun: "2026-07-22T08:00:00Z",
    nextRun: "2026-07-22T09:00:00Z",
    status: "Healthy",
    projectsCollected: 4,
    country: "United States",
  },
  {
    id: "CON-02",
    name: "UK Contracts Finder",
    sourceType: "Government Procurement API",
    baseUrl: "https://www.contractsfinder.service.gov.uk/api/rest/2/search_notices/json",
    authType: "None",
    enabled: true,
    schedule: "Hourly",
    rateLimitPerMin: 30,
    pagination: "Page",
    retryPolicy: "Exponential backoff, 3 attempts",
    lastRun: "2026-07-22T08:15:00Z",
    nextRun: "2026-07-22T09:15:00Z",
    status: "Healthy",
    projectsCollected: 3,
    country: "United Kingdom",
  },
  {
    id: "CON-03",
    name: "TED Europa (EU Tenders)",
    sourceType: "Open Data Portal",
    baseUrl: "https://ted.europa.eu/api/v3.0/notices/search",
    authType: "Bearer Token",
    enabled: true,
    schedule: "Daily",
    rateLimitPerMin: 20,
    pagination: "Cursor",
    retryPolicy: "Linear, 5 attempts",
    lastRun: "2026-07-22T02:00:00Z",
    nextRun: "2026-07-23T02:00:00Z",
    status: "Degraded",
    projectsCollected: 2,
    country: "European Union",
  },
  {
    id: "CON-04",
    name: "AngelList Startup Jobs RSS",
    sourceType: "RSS Feed",
    baseUrl: "https://angel.co/feed.rss",
    authType: "None",
    enabled: true,
    schedule: "Every 15 minutes",
    rateLimitPerMin: 120,
    pagination: "None",
    retryPolicy: "Exponential backoff, 3 attempts",
    lastRun: "2026-07-22T08:45:00Z",
    nextRun: "2026-07-22T09:00:00Z",
    status: "Healthy",
    projectsCollected: 2,
    country: "Global",
  },
  {
    id: "CON-05",
    name: "GeM Government e-Marketplace",
    sourceType: "Government Procurement API",
    baseUrl: "https://api.gem.gov.in/tenders/v1",
    authType: "OAuth",
    enabled: false,
    schedule: "Hourly",
    rateLimitPerMin: 45,
    pagination: "Page",
    retryPolicy: "Exponential backoff, 3 attempts",
    lastRun: "2026-07-21T18:00:00Z",
    nextRun: "—",
    status: "Idle",
    projectsCollected: 1,
    country: "India",
  },
  {
    id: "CON-06",
    name: "TenderLink ANZ Feed",
    sourceType: "Public Tender API",
    baseUrl: "https://api.tenderlink.com/v2/notices",
    authType: "API Key",
    enabled: true,
    schedule: "Hourly",
    rateLimitPerMin: 40,
    pagination: "Offset",
    retryPolicy: "Exponential backoff, 3 attempts",
    lastRun: "2026-07-22T08:05:00Z",
    nextRun: "2026-07-22T09:05:00Z",
    status: "Error",
    projectsCollected: 3,
    country: "Australia",
  },
];

export const CONNECTOR_LOGS: ConnectorLog[] = [
  { id: "LOG-1", connectorId: "CON-01", timestamp: "2026-07-22T08:00:12Z", level: "INFO", message: "Fetched page 1/3 — 20 notices", itemsFetched: 20, durationMs: 842 },
  { id: "LOG-2", connectorId: "CON-01", timestamp: "2026-07-22T08:00:15Z", level: "INFO", message: "Deduplicated 16 existing, upserted 4 new projects", itemsFetched: 4, durationMs: 210 },
  { id: "LOG-3", connectorId: "CON-06", timestamp: "2026-07-22T08:05:03Z", level: "ERROR", message: "HTTP 429 Too Many Requests — backing off 30s", itemsFetched: 0, durationMs: 120 },
  { id: "LOG-4", connectorId: "CON-03", timestamp: "2026-07-22T02:00:41Z", level: "WARN", message: "Response latency 4.2s exceeds SLA threshold", itemsFetched: 12, durationMs: 4200 },
  { id: "LOG-5", connectorId: "CON-04", timestamp: "2026-07-22T08:45:01Z", level: "INFO", message: "RSS parsed — 8 items, 2 matched keyword filters", itemsFetched: 2, durationMs: 96 },
  { id: "LOG-6", connectorId: "CON-02", timestamp: "2026-07-22T08:15:22Z", level: "INFO", message: "Upserted 3 projects, updated 1 changed deadline", itemsFetched: 3, durationMs: 540 },
];

export const ALL_CATEGORIES = CATEGORIES;
